/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : new Project
 #	author : Moussa BELLAHCENE
 #	13/04/2017
 #
 # --------------------------------------------------------------------------------*/


enum{
	eCMD_new_Command1 = 1
};
void InitPlugin();
void DeinitPlugin();

// --- new theme1
void new_Command1( PA_PluginParameters params );
