/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : new Project
 #	author : Moussa BELLAHCENE
 #	13/04/2017
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

void PluginMain( PA_long32 selector, PA_PluginParameters params )
{
	switch( selector )
	{
		case kInitPlugin :
			InitPlugin();
			break;

		case kDeinitPlugin :
			DeinitPlugin();
			break;

// --- new theme1

		case eCMD_new_Command1 :
			new_Command1( params );
			break;

	}
}

void InitPlugin()
{
	// write initialisation code here...
}

void DeinitPlugin()
{
	// write deinitialisation code here...
}

// ---------------------------------- new theme1 ----------------------------------


void new_Command1( PA_PluginParameters params )
{
	PA_long32 Param1;
	PA_Unichar* Param2_uchars;
	PA_Unistring* Param2;
	PA_long32 returnValue;

	Param1 = PA_GetLongParameter( params, 1 );
	Param2 = PA_GetStringParameter( params, 2 );
	Param2_uchars = PA_GetUnistring( Param2 );

	// --- write the code of new_Command1 here...

	PA_ReturnLong( params, returnValue );
}

